//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniSore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSale
    {
        public int SaleID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> SaleCategory { get; set; }
    
        public virtual TblCategory TblCategory { get; set; }
    }
}
